# build
markdown: kramdown
permalink: none
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
layouts_dir: ./_layouts
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# Google analytics
google_analytics: 'UA-50083848-999'
# theme
alwaysuneven:
  name: Always Uneven
  author:
    name: Marcelo Garcia
  lang: en
gems:
  - jekyll-redirect-from